/* 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
function isEven(num) {
    if (num % 2 === 0) {
        return true;
    } else {
        return false;
    }
}

function fibbonacci(n) {
    let sequence = [1,2];

    for (let i = 2; i < n; i++) {
        const nextNum = sequence[i - 1] + sequence[i - 2];
        if (nextNum < n) {
            sequence.push(nextNum);
        }
    }

    sequence = sequence.filter(isEven).reduce((a,b) => {
        return a + b;
    })

    return sequence;
}

console.log(fibbonacci(4000000));